<?php
use PHPUnit\Framework\TestCase;


class evaluateTest extends TestCase
{

    var $evaluate;

    public function __construct()
    {
        $this->evaluate = new evaluate();
    }

    public function testAllHands()
    {
        // hands.json file generated by hand using list at: http://suffe.cool/poker/7462.html    

        $suitOrder = array('c','h','d','s','c');
        $hands = json_decode(file_get_contents("hands.json"));

        for ($i = 0; $i < count($hands); $i++) 
        {
            $cards = array();

            for ($k = 0; $k < count($hands[$i]->cards); $k++)
            {
                if ($hands[$i]->suited)
                {
                    $suit = 'd';
                }
                else
                {
                    $suit = $suitOrder[$k];
                }

                $cards[]=new card($hands[$i]->cards[$k], $suit);


            }

            $this->assertEquals(
                $i + 1,
                $this->evaluate->getValue($cards)
            );


        }



    }

}

?>